name: bugaoshan
description: Explore everything, all on the Bugaoshan.
publish_to: none
version: 0.6.0
environment:
  sdk: ^3.10.4
dependencies:
  flutter:
    sdk: flutter
  photo_view: ^0.15.0
  cupertino_icons: ^1.0.8
  get_it: ^9.2.0
  injectable: null
  shared_preferences: null
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_colorpicker: null
  url_launcher: null
  package_info_plus: null
  web: any
  async: any
  http: ^1.2.0
  hive_ce: ^2.19.3
  path_provider: ^2.1.5
  path: ^1.9.0
  dart_sm: ^0.1.4
  flutter_secure_storage: ^10.0.0
  flutter_litert: ^2.2.0 #note: GPU backend is manually removed in android\app\build.gradle.kts
  image: ^4.8.0
  pub_semver: ^2.1.4
  archive: ^4.0.9
  os_type: ^0.2.2
  file_picker: ^11.0.2
  flutter_markdown_plus: ^1.0.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: null
  injectable_generator: null
  flutter_launcher_icons: ^0.14.1
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/avater.png
    - assets/icon.png
    - assets/universal-login-ocr.tflite
    - assets/scripts/
flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: assets/icon.png
  windows:
    generate: true
    image_path: assets/icon.png
  macos:
    generate: true
    image_path: assets/icon.png
  linux:
    generate: true
    image_path: assets/icon.png
  image_path: assets/icon.png
