name: bugaoshan
description: Explore everything, all on the Bugaoshan.
publish_to: none
version: 0.5.3
environment:
  sdk: ^3.10.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get_it: ^9.2.0
  injectable: null
  shared_preferences: null
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_colorpicker: null
  url_launcher: null
  package_info_plus: null
  web: any
  async: any
  http: ^1.2.0
  hive_ce: ^2.19.3
  path_provider: ^2.1.5
  dart_sm: ^0.1.4
  flutter_secure_storage: ^9.2.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: null
  injectable_generator: null
  flutter_launcher_icons: ^0.14.1
flutter:
  uses-material-design: true
  generate: true
  assets:
  - assets/avater.png
flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: assets/icon.png
  windows:
    generate: true
    image_path: assets/icon.png
  macos:
    generate: true
    image_path: assets/icon.png
  linux:
    generate: true
    image_path: assets/icon.png
  image_path: assets/icon.png
