// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for English (`en`).
class AppLocalizationsEn extends AppLocalizations {
  AppLocalizationsEn([String locale = 'en']) : super(locale);

  @override
  String get bugaoshan => 'Bugaoshan';

  @override
  String get selfLanguage => 'English';

  @override
  String get course => 'Course';

  @override
  String get profile => 'Profile';

  @override
  String get campus => 'Campus';

  @override
  String get classroomQuery => 'Classroom Query';

  @override
  String get classroomQueryDesc =>
      'Check classroom availability and borrowing status';

  @override
  String get selectCampus => 'Select Campus';

  @override
  String get selectBuilding => 'Select Building';

  @override
  String get allBuildings => 'All Buildings';

  @override
  String get seats => 'seats';

  @override
  String get free => 'Free';

  @override
  String get inClass => 'In Class';

  @override
  String get borrowed => 'Borrowed';

  @override
  String get period => 'Period';

  @override
  String get loading => 'Loading...';

  @override
  String get loadFailed => 'Load failed, tap to retry';

  @override
  String get campusNetworkRequired =>
      'This feature is only available on campus network. Please connect to campus Wi-Fi or use the school VPN.';

  @override
  String get appOnly => 'Available on App only';

  @override
  String get softwareSetting => 'Software Setting';

  @override
  String get followSystem => 'Follow System';

  @override
  String get modifyLanguage => 'Modify Language';

  @override
  String get current => 'Current';

  @override
  String get animationDuration => 'Duration';

  @override
  String get confirm => 'Confirm';

  @override
  String currentAnimationDuration(Object value) {
    return 'Current Animation Duration: $value ms';
  }

  @override
  String animationDurationUpdated(Object value) {
    return 'Animation Duration updated to $value ms';
  }

  @override
  String get animationDurationHint =>
      'Hint: Adjust the slider to preview the animation, click Confirm to save the settings';

  @override
  String get themeColor => 'Theme Color';

  @override
  String get changeThemeColor => 'Change Theme Color';

  @override
  String get confirmButton => 'Confirm';

  @override
  String get customizedColorHint =>
      'Customized color is generated by color seed';

  @override
  String get tips => 'Tips';

  @override
  String get resetToDefault => 'Reset to Default';

  @override
  String get blockPicker => 'Block';

  @override
  String get materialPicker => 'Material';

  @override
  String get advancedPicker => 'Advanced';

  @override
  String get about => 'About';

  @override
  String get developmentTeam => 'Developer Team';

  @override
  String get projectInfo => 'Project Info';

  @override
  String get appName => 'App Name';

  @override
  String get version => 'Version';

  @override
  String get description => 'Description';

  @override
  String get appDescription => 'A simple and practical course management app';

  @override
  String get contactUs => 'Contact Us';

  @override
  String developedBy(Object team) {
    return 'Developed by $team';
  }

  @override
  String get externalResources => 'External Resources';

  @override
  String get projectRepository => 'Project Repository';

  @override
  String get clearAllData => 'Clear All Data';

  @override
  String get confirmMessage => 'Are you sure?';

  @override
  String get environmentInfo => 'Environment Info';

  @override
  String get scheduleSetting => 'Schedule Setting';

  @override
  String get scheduleManagement => 'Schedule Management';

  @override
  String get globalSetting => 'Global Setting';

  @override
  String get addCourse => 'Add Course';

  @override
  String get editCourse => 'Edit Course';

  @override
  String get deleteCourse => 'Delete Course';

  @override
  String get deleteCourseConfirm =>
      'Are you sure you want to delete this course?';

  @override
  String get courseName => 'Course Name';

  @override
  String get teacher => 'Teacher';

  @override
  String get location => 'Location';

  @override
  String get courseColor => 'Course Color';

  @override
  String get week => 'Week';

  @override
  String get startWeek => 'Start Week';

  @override
  String get endWeek => 'End Week';

  @override
  String get dayOfWeek => 'Day of Week';

  @override
  String get startSection => 'Start Section';

  @override
  String get endSection => 'End Section';

  @override
  String get monday => 'Mon';

  @override
  String get tuesday => 'Tue';

  @override
  String get wednesday => 'Wed';

  @override
  String get thursday => 'Thu';

  @override
  String get friday => 'Fri';

  @override
  String get saturday => 'Sat';

  @override
  String get sunday => 'Sun';

  @override
  String currentWeek(Object week) {
    return 'Week $week';
  }

  @override
  String get thisWeek => 'This week';

  @override
  String weekRange(Object end, Object start) {
    return 'Week $start - $end';
  }

  @override
  String get weekType => 'Week Type';

  @override
  String get everyWeek => 'Every Week';

  @override
  String get oddWeek => 'Odd Week';

  @override
  String get evenWeek => 'Even Week';

  @override
  String get section => 'Sec';

  @override
  String get sectionCount => 'Sections per Day';

  @override
  String get timeSlot => 'Time Slot';

  @override
  String get startTime => 'Start Time';

  @override
  String get endTime => 'End Time';

  @override
  String get semesterConfig => 'Semester Config';

  @override
  String get semesterName => 'Semester Name';

  @override
  String get semesterStartDate => 'Semester Start Date';

  @override
  String get semesterEndDate => 'Semester End Date';

  @override
  String get displaySetting => 'Display Setting';

  @override
  String get colorOpacity => 'Color Opacity';

  @override
  String get fontSize => 'Font Size';

  @override
  String get showTeacher => 'Show Teacher';

  @override
  String get showLocation => 'Show Location';

  @override
  String get showWeekend => 'Show Weekend';

  @override
  String get save => 'Save';

  @override
  String get cancel => 'Cancel';

  @override
  String get delete => 'Delete';

  @override
  String get customColor => 'Custom Color';

  @override
  String get noCourseThisWeek => 'No courses this week';

  @override
  String get timeConflict => 'Time Conflict';

  @override
  String get timeConflictMessage =>
      'The selected time slot conflicts with an existing course.';

  @override
  String get fieldRequired => 'This field is required';

  @override
  String get invalidWeekRange =>
      'End week must be greater than or equal to start week';

  @override
  String get duplicateScheduleName => 'Schedule name already exists';

  @override
  String get exportSuccess => 'Schedule data copied to clipboard';

  @override
  String get importSchedule => 'Import Schedule';

  @override
  String get importFromShare => 'Import from Share';

  @override
  String get importFromJwxt => 'Import from Education System';

  @override
  String get importDataHint => 'Paste JSON data here...';

  @override
  String get importSuccess => 'Schedule imported successfully';

  @override
  String get importFailed => 'Import failed, please check data format';

  @override
  String get importedScheduleDefaultName => 'Imported Schedule';

  @override
  String importNameConflictHint(Object name) {
    return 'Name \"$name\" already exists, please rename:';
  }

  @override
  String get importNameSuffix => '(Import)';

  @override
  String get defaultScheduleName => 'Default Schedule';

  @override
  String deleteScheduleConfirm(Object name) {
    return 'Are you sure you want to delete schedule \"$name\"?';
  }

  @override
  String get exportSchedule => 'Export Schedule';

  @override
  String get copySuffix => ' (Copy)';

  @override
  String get notThisWeek => '[Not this week]';

  @override
  String actualCurrentWeek(Object week) {
    return 'Week $week';
  }

  @override
  String totalWeeksSubtitle(Object count) {
    return '$count weeks';
  }

  @override
  String get invalidSectionRange =>
      'End section must be greater than start section';

  @override
  String get crossPeriodError => 'Cross Period Error';

  @override
  String get crossPeriodErrorMessage =>
      'A course cannot span across morning, afternoon, or evening periods.';

  @override
  String totalWeeks(Object value) {
    return 'Total Weeks: $value';
  }

  @override
  String get morning => 'Morning';

  @override
  String get afternoon => 'Afternoon';

  @override
  String get evening => 'Evening';

  @override
  String get courseDuration => 'Course Duration (mins)';

  @override
  String get breakDuration => 'Break Duration (mins)';

  @override
  String get autoSyncTime => 'Auto-calculate subsequent times';
}
