// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for English (`en`).
class AppLocalizationsEn extends AppLocalizations {
  AppLocalizationsEn([String locale = 'en']) : super(locale);

  @override
  String get rubbishPlan => 'Rubbish Plan';

  @override
  String get selfLanguage => 'English';

  @override
  String get course => 'Course';

  @override
  String get profile => 'Profile';

  @override
  String get softwareSetting => 'Software Setting';

  @override
  String get followSystem => 'Follow System';

  @override
  String get modifyLanguage => 'Modify Language';

  @override
  String get current => 'Current';

  @override
  String get animationDuration => 'Duration';

  @override
  String get confirm => 'Confirm';

  @override
  String currentAnimationDuration(Object value) {
    return 'Current Animation Duration: $value ms';
  }

  @override
  String animationDurationUpdated(Object value) {
    return 'Animation Duration updated to $value ms';
  }

  @override
  String get animationDurationHint =>
      'Hint: Adjust the slider to preview the animation, click Confirm to save the settings';

  @override
  String get themeColor => 'Theme Color';

  @override
  String get changeThemeColor => 'Change Theme Color';

  @override
  String get confirmButton => 'Confirm';

  @override
  String get customizedColorHint =>
      'Customized color is generated by color seed';

  @override
  String get tips => 'Tips';

  @override
  String get resetToDefault => 'Reset to Default';

  @override
  String get blockPicker => 'Block';

  @override
  String get materialPicker => 'Material';

  @override
  String get advancedPicker => 'Advanced';

  @override
  String get about => 'About';

  @override
  String get developmentTeam => 'Developer Team';

  @override
  String get projectInfo => 'Project Info';

  @override
  String get appName => 'App Name';

  @override
  String get version => 'Version';

  @override
  String get description => 'Description';

  @override
  String get appDescription => 'A simple and practical course management app';

  @override
  String get contactUs => 'Contact Us';

  @override
  String developedBy(Object team) {
    return 'Developed by $team';
  }

  @override
  String get externalResources => 'External Resources';

  @override
  String get projectRepository => 'Project Repository';

  @override
  String get clearAllData => 'Clear All Data';

  @override
  String get confirmMessage => 'Are you sure?';

  @override
  String get environmentInfo => 'Environment Info';

  @override
  String get scheduleSetting => 'Schedule Setting';

  @override
  String get globalSetting => 'Global Setting';
}
