name: Build Test APK

on:
  workflow_dispatch:
  push:
    branches:
      - test/android-reminder

jobs:
  build:
    name: Build Test Android APK
    runs-on: ubuntu-latest
    env:
      PUB_HOSTED_URL: https://pub.flutter-io.cn
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup build environment
        uses: ./.github/actions/setup

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: Build Debug APK
        run: flutter build apk --debug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: Bugaoshan-Test-Reminder-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
          if-no-files-found: error
